const PDFDocument = require('pdfkit')
const {
  registerPdfFonts,
  drawPdfHeader,
  drawPdfTitleBar,
  drawPdfSummaryCards,
  drawPdfSectionTable,
  drawPdfSignatureBlock,
  drawPdfFooter,
} = require('./pdfStyle.service')

function labelize(value = '') {
  return String(value)
    .toLowerCase()
    .replaceAll('_', ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

function computeSeverity(log) {
  const action = String(log.action || '').toUpperCase()
  const module = String(log.module || '').toUpperCase()
  const description = String(log.description || '').toLowerCase()
  if (action === 'DELETE') return 'Critical'
  if (description.includes('backdated') || description.includes('override')) return 'Warning'
  if (action === 'LOGIN' || module === 'SECURITY') return 'Info'
  if (action === 'RECONCILE' || ['DONATIONS', 'EXPENSES', 'CASHBOOK', 'RECONCILIATION'].includes(module)) return 'Financial'
  if (description.includes('verify') || description.includes('audit')) return 'Audit Sensitive'
  return 'Info'
}

function moduleLabel(moduleName) {
  const map = {
    DONATIONS: 'Donations',
    EXPENSES: 'Expenses',
    TRUSTEES: 'Trustees',
    SECURITY: 'Security',
    RECONCILIATION: 'Reconciliation',
    CASHBOOK: 'Cash Book',
    REPORTS: 'Reports',
  }
  return map[String(moduleName || '').toUpperCase()] || labelize(moduleName)
}

async function generateAuditActivityPdf({ trustName, generatedBy, periodLine, logs }) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: 28, bufferPages: true })
      registerPdfFonts(doc, 'audit')
      const chunks = []
      doc.on('data', (chunk) => chunks.push(chunk))
      doc.on('end', () => resolve(Buffer.concat(chunks)))
      doc.on('error', reject)

      const summary = {
        total: logs.length,
        financial: logs.filter((l) => computeSeverity(l) === 'Financial').length,
        highRisk: logs.filter((l) => ['Critical', 'Warning', 'Audit Sensitive'].includes(computeSeverity(l))).length,
        login: logs.filter((l) => String(l.action || '').toUpperCase() === 'LOGIN').length,
      }

      const header = drawPdfHeader(doc, {
        trustName,
        subtitle: 'Audit Trail & Activity Register',
        metadata: [
          `Period: ${periodLine}`,
          `Generated By: ${generatedBy}`,
          `Generated On: ${new Date().toLocaleString('en-IN')}`,
          'Audit trail protected and read-only',
        ],
      })
      let y = drawPdfTitleBar(doc, { title: 'Audit Trail & Activity Register', y: header.nextY })
      y = drawPdfSummaryCards(doc, {
        y,
        cards: [
          { label: 'Total Activities', value: String(summary.total) },
          { label: 'Financial Actions', value: String(summary.financial) },
          { label: 'Login Activity', value: String(summary.login) },
          { label: 'High Risk Activities', value: String(summary.highRisk), alert: summary.highRisk > 0 },
        ],
      })

      const rows = logs.map((log) => ({
        timestamp: new Date(log.created_at).toLocaleString('en-IN'),
        performedBy: log.user?.name || log.user?.username || 'System',
        module: moduleLabel(log.module),
        action: labelize(log.action),
        severity: computeSeverity(log),
        description: log.description || '-',
      }))

      y = drawPdfSectionTable(doc, {
        title: 'Activity Register',
        rows,
        columns: [
          { key: 'timestamp', label: 'Timestamp', width: 118 },
          { key: 'performedBy', label: 'Performed By', width: 126 },
          { key: 'module', label: 'Module', width: 102 },
          { key: 'action', label: 'Action', width: 128 },
          { key: 'severity', label: 'Severity', width: 108 },
          { key: 'description', label: 'Description', width: 276 },
        ],
        startY: y,
      })

      drawPdfSignatureBlock(doc, { y: y + 8 })
      drawPdfFooter(doc, {
        text: `System Generated Audit Report | Generated on ${new Date().toLocaleString('en-IN')} | Powered by FastLegal Technologies Pvt Ltd`,
      })
      doc.end()
    } catch (err) {
      reject(err)
    }
  })
}

module.exports = {
  generateAuditActivityPdf,
}
