const PDFDocument = require('pdfkit')
const {
  registerPdfFonts,
  formatInrPdf,
  drawPdfHeader,
  drawPdfTitleBar,
  drawPdfSummaryCards,
  drawPdfSectionTable,
  drawPdfFooter,
} = require('./pdfStyle.service')

function fmtDate(value) {
  if (!value) return '-'
  return new Date(value).toLocaleDateString('en-IN')
}

function fmtDateTime(value) {
  if (!value) return '-'
  return new Date(value).toLocaleString('en-IN')
}


async function generateReconciliationPdf({
  trust,
  selectedPeriod,
  generatedBy,
  totals,
  pendingReceipts,
  pendingPayments,
  matchedEntries,
}) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: 28, bufferPages: true })
      registerPdfFonts(doc, 'recon')
      const buffers = []
      doc.on('data', (chunk) => buffers.push(chunk))
      doc.on('end', () => resolve(Buffer.concat(buffers)))
      doc.on('error', reject)

      const left = 28
      const contentWidth = doc.page.width - left * 2

      const header = drawPdfHeader(doc, {
        trustName: trust?.name_hindi || trust?.name || 'Trust',
        subtitle: trust?.address || 'Bank Reconciliation Register',
        metadata: [
          `Period: ${selectedPeriod}`,
          `Generated By: ${generatedBy}`,
          `Generated On: ${new Date().toLocaleString('en-IN')}`,
          `Last Reconciled: ${fmtDate(totals.last_reconciliation_date)}`,
        ],
      })

      let cursorY = drawPdfTitleBar(doc, { title: 'Bank Reconciliation Register', y: header.nextY })
      cursorY = drawPdfSummaryCards(doc, {
        y: cursorY,
        cards: [
          { label: 'Pending Receipts', value: `${totals.pending_receipts_count || 0} / ${formatInrPdf(totals.unreconciled_donation_amount)}` },
          { label: 'Pending Payments', value: `${totals.pending_payments_count || 0} / ${formatInrPdf(totals.unreconciled_expense_amount)}` },
          { label: 'Matched Entries', value: `${totals.matched_count || 0} / ${formatInrPdf(totals.matched_amount)}` },
          { label: 'Settlement Difference', value: formatInrPdf(totals.settlement_difference), alert: Number(totals.settlement_difference || 0) !== 0 },
        ],
      })
      const pendingReceiptRows = pendingReceipts.map((row) => ({
        date: fmtDate(row.donation_date),
        ref: row.receipt_number || row.id,
        particulars: `Donation - ${row.donor_name || '-'}`,
        mode: row.payment_mode || '-',
        bankRef: row.bank_ref || row.upi_ref || row.cheque_number || '-',
        amount: formatInrPdf(row.amount),
        status: row.bank_ref || row.upi_ref || row.cheque_number ? 'Partially Matched' : 'Pending',
      }))
      cursorY = drawPdfSectionTable(doc, {
        title: 'Pending Receipts',
        rows: pendingReceiptRows,
        columns: [
          { key: 'date', label: 'Date', width: 72 },
          { key: 'ref', label: 'Voucher Ref.', width: 124 },
          { key: 'particulars', label: 'Particulars', width: 250 },
          { key: 'mode', label: 'Payment Mode', width: 84 },
          { key: 'bankRef', label: 'Bank Reference', width: 134 },
          { key: 'amount', label: 'Amount', width: 96, align: 'right' },
          { key: 'status', label: 'Status', width: 96 },
        ],
        startY: cursorY,
      })

      const pendingPaymentRows = pendingPayments.map((row) => ({
        date: fmtDate(row.expense_date),
        ref: row.voucher_number || row.reference || row.id,
        particulars: `Expense - ${row.description || '-'}`,
        mode: row.payment_mode || row.payment_channel || 'BANK',
        bankRef: row.bank_ref || row.transaction_id || row.cheque_number || row.reference || '-',
        amount: formatInrPdf(row.amount),
        status: row.bank_ref || row.transaction_id || row.reference ? 'Partially Matched' : 'Pending',
      }))
      cursorY = drawPdfSectionTable(doc, {
        title: 'Pending Payments',
        rows: pendingPaymentRows,
        columns: [
          { key: 'date', label: 'Date', width: 72 },
          { key: 'ref', label: 'Voucher Ref.', width: 124 },
          { key: 'particulars', label: 'Particulars', width: 250 },
          { key: 'mode', label: 'Payment Mode', width: 84 },
          { key: 'bankRef', label: 'Bank Reference', width: 134 },
          { key: 'amount', label: 'Amount', width: 96, align: 'right' },
          { key: 'status', label: 'Status', width: 96 },
        ],
        startY: cursorY,
      })

      const matchedRows = matchedEntries.map((row) => ({
        date: fmtDate(row.matched_on),
        ref: row.voucher_ref || '-',
        type: row.entry_type || '-',
        particulars: row.particulars || '-',
        amount: formatInrPdf(row.amount),
        matchedBy: row.matched_by || 'System',
        matchedOn: fmtDateTime(row.matched_on),
      }))
      drawPdfSectionTable(doc, {
        title: 'Reconciled Entries',
        rows: matchedRows,
        columns: [
          { key: 'date', label: 'Date', width: 70 },
          { key: 'ref', label: 'Voucher Ref.', width: 120 },
          { key: 'type', label: 'Type', width: 62 },
          { key: 'particulars', label: 'Particulars', width: 280 },
          { key: 'amount', label: 'Amount', width: 96, align: 'right' },
          { key: 'matchedBy', label: 'Matched By', width: 92 },
          { key: 'matchedOn', label: 'Matched On', width: 118 },
        ],
        startY: cursorY,
      })

      drawPdfFooter(doc, {
        text: `System Generated Reconciliation Report | Generated on ${new Date().toLocaleString('en-IN')} | Powered by FastLegal Technologies Pvt Ltd`,
      })

      doc.end()
    } catch (error) {
      reject(error)
    }
  })
}

module.exports = {
  generateReconciliationPdf,
}
