const PDFDocument = require('pdfkit')
const {
  registerPdfFonts,
  formatInrPdf,
  drawPdfHeader,
  drawPdfTitleBar,
  drawPdfSummaryCards,
  drawPdfSectionTable,
  drawPdfSignatureBlock,
  drawPdfFooter,
} = require('./pdfStyle.service')

function fmtDate(d) {
  if (!d) return '-'
  return new Date(d).toLocaleDateString('en-IN')
}

async function generateReportsPdf({
  type,
  trustName,
  generatedBy,
  dateFrom,
  dateTo,
  donations,
  expenses,
  trustees,
  donors,
  reconciliation,
}) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: 24, bufferPages: true })
      registerPdfFonts(doc, 'reports')
      const chunks = []
      doc.on('data', (c) => chunks.push(c))
      doc.on('end', () => resolve(Buffer.concat(chunks)))
      doc.on('error', reject)

      const periodLine = dateFrom && dateTo ? `${dateFrom} to ${dateTo}` : 'All records'
      const totalDonationAmount = (donations || []).reduce((sum, row) => sum + Number(row.amount || 0), 0)
      const totalExpenseAmount = (expenses || []).reduce((sum, row) => sum + Number(row.amount || 0), 0)
      const netBalance = totalDonationAmount - totalExpenseAmount
      const pendingReconciliation =
        Number(reconciliation?.pending_receipts_count || 0) + Number(reconciliation?.pending_payments_count || 0)

      const header = drawPdfHeader(doc, {
        trustName,
        subtitle: 'Trust Financial Reporting & Compliance Center',
        metadata: [
          `Report Type: ${type.replaceAll('_', ' ').replace(/\b\w/g, (ch) => ch.toUpperCase())}`,
          `Period: ${periodLine}`,
          `Generated By: ${generatedBy}`,
          `Generated On: ${new Date().toLocaleString('en-IN')}`,
        ],
      })

      const reportTitles = {
        donations: 'Donation Register',
        expenses: 'Expense Register',
        full: 'Full Financial Report',
        compliance: 'Compliance Report',
        audit_pack: 'Audit Pack',
      }
      let y = drawPdfTitleBar(doc, { title: reportTitles[type] || 'Financial Report', y: header.nextY })
      y = drawPdfSummaryCards(doc, {
        y,
        cards: [
          { label: 'Total Donations', value: formatInrPdf(totalDonationAmount) },
          { label: 'Total Expenses', value: formatInrPdf(totalExpenseAmount) },
          { label: 'Net Surplus / Deficit', value: formatInrPdf(netBalance), alert: netBalance < 0 },
          { label: 'Pending Reconciliation', value: `${pendingReconciliation} entries`, alert: pendingReconciliation > 0 },
        ],
      })

      const donationsRows = (donations || []).map((d) => ({
        date: fmtDate(d.donation_date),
        ref: d.receipt_number || '-',
        donor: d.donor_name || '-',
        mode: d.payment_mode || '-',
        amount: formatInrPdf(d.amount),
      }))
      const expenseRows = (expenses || []).map((e) => ({
        date: fmtDate(e.expense_date),
        ref: e.voucher_number || e.reference || e.id,
        category: e.category || '-',
        particulars: e.description || '-',
        amount: formatInrPdf(e.amount),
      }))
      const trusteeRows = (trustees || []).map((t) => ({
        name: t.name,
        role: t.role || '-',
        amount: formatInrPdf(t.total_amount),
        count: t.contribution_count || 0,
      }))
      const donorRows = (donors || []).slice(0, 20).map((d) => ({
        name: d.donor_name || '-',
        mobile: d.donor_mobile || '-',
        city: d.donor_city || '-',
        amount: formatInrPdf(d.total_amount),
        count: d.donation_count || 0,
      }))

      if (type === 'donations' || type === 'full' || type === 'compliance' || type === 'audit_pack') {
        y = drawPdfSectionTable(doc, {
          y,
          title: 'Donation Collection Register',
          columns: [
            { key: 'date', label: 'Date', width: 78 },
            { key: 'ref', label: 'Receipt No', width: 126 },
            { key: 'donor', label: 'Donor', width: 294 },
            { key: 'mode', label: 'Payment Mode', width: 94 },
            { key: 'amount', label: 'Amount', width: 128, align: 'right' },
          ],
          rows: donationsRows,
        })
      }

      if (type === 'expenses' || type === 'full' || type === 'audit_pack') {
        y = drawPdfSectionTable(doc, {
          y,
          title: 'Expense Register',
          columns: [
            { key: 'date', label: 'Date', width: 78 },
            { key: 'ref', label: 'Voucher Ref', width: 120 },
            { key: 'category', label: 'Category', width: 120 },
            { key: 'particulars', label: 'Particulars', width: 274 },
            { key: 'amount', label: 'Amount', width: 128, align: 'right' },
          ],
          rows: expenseRows,
        })
      }

      if (type === 'full' || type === 'audit_pack') {
        y = drawPdfSectionTable(doc, {
          y,
          title: 'Trustee Contribution Report',
          columns: [
            { key: 'name', label: 'Trustee', width: 280 },
            { key: 'role', label: 'Role', width: 210 },
            { key: 'amount', label: 'Contribution', width: 160, align: 'right' },
            { key: 'count', label: 'Count', width: 112, align: 'right' },
          ],
          rows: trusteeRows,
        })
      }

      if (type === 'full' || type === 'compliance' || type === 'audit_pack') {
        const highValueDonations = donationsRows.filter((d) => Number(String(d.amount).replace(/[^\d.]/g, '')) >= 10000).length
        const complianceRows = [
          { metric: '80G / PAN Verification Pending', value: `${(donations || []).filter((d) => !d.pan_number).length}` },
          { metric: 'Cash Donation Threshold Alerts', value: `${(donations || []).filter((d) => d.payment_mode === 'CASH' && Number(d.amount || 0) >= 10000).length}` },
          { metric: 'High Value Donations (>= Rs. 10,000)', value: `${highValueDonations}` },
          { metric: 'Pending Reconciliation Entries', value: `${pendingReconciliation}` },
        ]
        y = drawPdfSectionTable(doc, {
          y,
          title: 'Compliance Snapshot',
          columns: [
            { key: 'metric', label: 'Metric', width: 560 },
            { key: 'value', label: 'Count', width: 202, align: 'right' },
          ],
          rows: complianceRows,
        })
      }

      if (type === 'full' || type === 'audit_pack') {
        y = drawPdfSectionTable(doc, {
          y,
          title: 'Top Donor Summary',
          columns: [
            { key: 'name', label: 'Donor', width: 280 },
            { key: 'mobile', label: 'Mobile', width: 150 },
            { key: 'city', label: 'City', width: 142 },
            { key: 'amount', label: 'Total', width: 128, align: 'right' },
            { key: 'count', label: 'Count', width: 62, align: 'right' },
          ],
          rows: donorRows,
        })
      }

      drawPdfSignatureBlock(doc, { y: y + 6 })
      drawPdfFooter(doc, {
        text: `System Generated Financial Report | Generated on ${new Date().toLocaleString('en-IN')} | Powered by FastLegal Technologies Pvt Ltd`,
      })

      doc.end()
    } catch (err) {
      reject(err)
    }
  })
}

module.exports = {
  generateReportsPdf,
}
